export const cssContent = {
  name: "CSS",
  description: "Learn CSS - Style your web pages",
  lessons: [
    {
      id: 1,
      title: "Introduction & Types of CSS",
      icon: "🎨",
      content: "1.1 What is CSS?\nCSS (Cascading Style Sheets) is the language used to style the frontend of a website. While HTML provides the structure (like the bones), CSS provides the presentation (like the skin, hair, and clothes).\n1.2 Types of CSS:\n**1. Inline CSS**\nInline CSS is used to apply a unique style to a single HTML element. You add the style attribute directly inside the opening tag of the element.\nSyntax: `<tagname style=\"property:value;\">` \nExample:```html\n<p style=\"color:red;\">This is a red paragraph.</p>\n```\nBest For: Quick fixes or styling a single, specific element that won't be repeated.\n**2. Internal CSS**\nInternal (or embedded) CSS is used to define styles for a single HTML page. The CSS rules are placed inside a <style> element within the <head> section of the document.\nSyntax: Styles are wrapped in `<style>` tags.\nExample:```html\n<head>\n  <style>\n    body { background-color: linen; }\n    h1 { color: maroon; }\n  </style>\n</head>\n```\nBest For: When a single page has a unique look that shouldn't affect other pages.\n**3. External CSS**\nExternal CSS is the professional standard for web development. All styling rules are written in a separate file (with a .css extension), which is then linked to the HTML page.\nSyntax: Use the `<link>` tag in the <head> section to connect the file.\nExample:```html\n<link rel=\"stylesheet\" href=\"style.css\">\n```\nBest For: Large websites. It allows you to change the look of an entire site by editing just one file, improving performance and consistency.\n1.3 Cascading and Inheritance\nIn CSS, Cascading and Inheritance are the two fundamental sets of rules that determine which styles are applied to an element when multiple instructions conflict.\n**1. Cascading (The \"Priority\" Rules)**\nThe \"Cascade\" is the process of deciding which CSS rule \"wins\" based on three main factors:\n**Importance:** Rules marked with !important always win, regardless of other factors.\n**Specificity:** This is a score based on how specific a selector is.\n- ID selectors (#id) have the highest priority.\n- Class selectors (.class) have medium priority.\n- Element selectors (p, h1) have the lowest priority.\n**Source Order:** If two rules have the same importance and specificity, the one written last in the code wins.\n**2. Inheritance**\nInheritance is the way some CSS properties are passed down from a parent element to its children.\n**Inherited Properties:** Most text-related properties like color, font-family, and text-align are inherited by child elements automatically.\n**Non-Inherited Properties:** Layout-related properties like margin, padding, border, and width are not inherited; they must be defined for each element specifically."
    },
    {
      id: 2,
      title: "CSS Selectors",
      icon: "🔍",
      content: "2.1 What is a CSS Selector?\nCSS Selectors: A CSS selector \"selects\" the HTML element(s) you want to style. By using different types of selectors, you can be as broad as styling every paragraph on a page or as specific as styling only one single button.\n2.2 Types of CSS Selectors:\n**1. Simple Selectors**\n- Element Selector: Targets elements by their tag name.\n- Id Selector: Targets a single element with a unique id attribute. It uses the hash (#) character.\n- Class Selector: Targets elements with a specific class attribute. It uses a period (.) character.\n**2. Combinators**\n- Descendant Selector (space): Matches all elements that are descendants of a specified element.\n- Child Selector (>): Matches only the elements that are direct children of a specified parent.\n**3. Pseudo-classes**\n- :hover: Styles an element when you move your mouse over it.\n- :visited: Used to style links that the user has already clicked.\n- :nth-child(n): Targets the n-th child of a parent, which is great for styling alternating rows in a table.\nExample:```html\n<div class=\"lesson-card\" id=\"css-intro\">\n<h3>Lesson 1: CSS Introduction</h3>\n<p>Learn how to style your first webpage.</p>\n</div>\n<style>\n#css-intro { border-left: 5px solid #22c55e; }\n.lesson-card {\nbackground-color: #f9f9f9;\ncolor: #333;\nfont-family: Arial, sans-serif;\npadding: 15px;\nborder: 1px solid #ddd;\nborder-radius: 8px;\n}\n.lesson-card:hover { background-color: #f0fdf4; cursor: pointer; }\n</style>```"
    },
    {
      id: 3,
      title: "CSS Properties",
      icon: "🛠️",
      content: "3.1 what is css properties\nA CSS property is part of a declaration block that defines a specific style aspect, such as color, size, or font. Each property is followed by a colon and a value, ending with a semicolon.\n3.2 Categories of CSS Properties\n**1. Typography (Text Styles)**\nThese properties control how the text in your lessons looks to the user.\n**color:** Changes the color of the text.\n**font-size:** Sets how large or small the text appears.\n**2. Visual & Background Styles**\nThese define the \"skin\" of your webpage, like the color of the cards in your course list.\n**background-color:** Sets the color behind the content of an element.\n**background-image:** Places an image in the background of a section.\n**opacity:** Controls the transparency of an element.\n**font-family:** Defines the typeface (e.g., Arial, sans-serif).\n**text-align:** Controls horizontal alignment, such as centering a lesson title.\n**3. Text Decoration & Transformation**\nThese properties add style to the actual text content beyond just font size or color.\n**text-decoration:** Used to add or remove lines from text, like underline or none for links.\n**text-transform:** Controls capitalization, such as uppercase, lowercase, or capitalize.\n**letter-spacing:** Adjusts the space between characters for better readability.\n**line-height:** Sets the vertical space between lines of text.\n**4. Display & Visibility**\nThese properties determine how an element is shown on the page.\n**display:** Defines the layout type (e.g., block, inline, flex, or none to hide it entirely).\n**visibility:** Specifies whether an element is visible or hidden (unlike display: none, it still takes up space).\n**opacity:** Sets the transparency level from 0.0 (invisible) to 1.0 (solid).\nExample:```html\n<p class=\"lesson-title\">Lesson 3: CSS Properties</p>\n\n<style>\n  .lesson-title {\n    color: #2c3e50;           /* Sets the text color */\n    font-family: sans-serif;  /* Sets the font */\n    font-size: 18px;          /* Sets the text size */\n    text-transform: uppercase;/* Makes all letters capital */\n    text-decoration: underline;/* Adds a line under the text */\n    letter-spacing: 2px;      /* Adds space between characters */\n    cursor: help;             /* Changes mouse to a question mark icon */\n    font-weight: bold;        /* Makes the text thicker */\n  }\n</style>\n```"
    },
    {
      id: 4,
      title: "CSS Box Model",
      icon: "📦",
      content: "4.1 Box Model:\nThe Box Model is a set of rules that determines the total space an element occupies on a webpage. It consists of four distinct layers that wrap around the HTML content.\n4.2 Four Layers of the Box:\n**1.Content:** The innermost part where the actual text, images, or videos appear.\n**2.Padding:** The transparent space that sits inside the border, surrounding the content. It is used to push the content away from the edges of the box.\n**3.Border:** The line that wraps around the padding and content. You can control its thickness, style, and color.\n**4.Margin:** The transparent space outside the border. It is used to create space between the element and other elements around it.\n4.3 Types of Box Sizing:\nThere are two ways the browser calculates the width and height of an element. This is controlled by the box-sizing property:\n**content-box (Default):** If you set a width of 200px, that only applies to the content. Any padding or borders you add will make the total box wider than 200px.\n**border-box (Professional Standard):** If you set a width of 200px, the padding and borders are included inside that width. This makes it much easier to manage layouts without doing complex math.\nExample:```css\n.lesson-card {\n  width: 300px;        /* Sets the width of the box */\n  padding: 20px;       /* Space inside the border */\n  border: 5px solid;   /* The line around the padding */\n  margin: 15px;        /* Space outside the card */\n  box-sizing: border-box; /* Ensures the total width stays 300px */\n}\n```"
    },
    {
      id: 5,
      title: "CSS Positioning",
      icon: "📍",
      content: "5.1 what is positioning:\nThe position property specifies the type of positioning method used for an element. Once a position is set, you use the top, bottom, left, and right properties to move the element to its final coordinates.\n5.2 Types of Positioning:\n**1. Static**\n**Definition:** The default value for every HTML element.\n**Behavior:** Elements follow the normal page flow (one after another).\n**Constraint:** It is not affected by top, bottom, left, or right properties.\n**2. Relative**\n**Definition:** The element is positioned relative to its normal position.\n**Behavior:** Setting left: 20px; moves the element 20 pixels to the right of where it would usually sit.\n**Benefit:** The space it originally occupied remains empty and is not filled by other elements.\n**3. Fixed**\n**Definition:** The element is positioned relative to the viewport (the browser window).\n**Behavior:** It stays in the exact same place even when you scroll the page.\n**Use Case:** Used for navigation bars or \"Chat\" buttons that should always be visible.\n**4. Absolute**\n**Definition:** The element is removed from the normal flow and positioned relative to its nearest positioned ancestor (a parent with relative, absolute, or fixed position).\n**Behavior:** If it has no positioned parents, it uses the document body as its reference.\n**5. Sticky**\n**Definition:** A hybrid of relative and fixed.\n**Behavior:** It acts as relative until the user scrolls to a specific point, then it \"sticks\" to that position like a fixed element.\n**Use Case:** Often used for section headings in a long list of courses.\nExample:```css\n.lesson-card {\n  position: relative; /* Acts as the anchor for the badge */\n  border: 1px solid #ddd;\n  padding: 20px;\n}\n\n.new-badge {\n  position: absolute; /* Placed exactly inside the card */\n  top: 0;\n  right: 0;\n  background-color: green;\n  color: white;\n}\n```"
    },
  ]
};
