export const javascriptContent = {
  name: "JavaScript",
  description: "Learn JavaScript - Add interactivity to your websites",
  lessons: [
    {
      id: 1,
      title: "JavaScript Introduction",
      icon: "⚡",
      content: "1.1 what is javascript?:\nJavaScript is a high-level, interpreted scripting language designed to add dynamic behavior and interactivity to web pages. It acts as the \"brain\" of a website, executing complex logic and responding to user actions directly within the browser.\n1.2 types of javascript:\n**1. Internal JavaScript**\nInternal JS is written directly inside the HTML file using the <script> tag. The browser reads the code as it parses the HTML.\n**Placement:** Usually placed at the bottom of the <body> tag so the HTML structure loads before the script runs.\n**Best For:** Small, one-off scripts, quick prototypes, or pages that require unique logic not shared with other pages.\n**Example:**```html\n<script>\n  console.log(\"This code runs internally!\");\n</script>```\n**2. External JavaScript (The Professional Standard)**\nExternal JS involves writing your code in a separate file with a .js extension and linking it to your HTML.\n**How it works:** You use the src attribute within the <script> tag to point to the file location.\n**Why it's preferred:**\n**Cleanliness:** Keeps your HTML file from becoming cluttered.\n**Reusability:** You can link the same .js file to multiple HTML pages.\n**Performance:** Browsers \"cache\" (save) external JS files. If a user visits a second page using the same script, it loads instantly.\n**Example:**```html\n<script src=\"js/app.js\"></script>```\n**1.3. The Engine: How Browsers \"Think\"**\nComputers cannot naturally read the text you write in a .js file. They require an Engine to translate it.\n**The V8 Engine:** Developed by Google for Chrome (and used in Node.js), this is the most famous engine.\n**Just-In-Time (JIT) Compilation:** Unlike older languages that compiled code all at once before running, modern JS engines compile code while it's running. This makes it incredibly fast.\n**The Process:** The engine parses your code into an Abstract Syntax Tree (AST) and then converts it into machine code that the computer's CPU can execute."
    },
    {
      id: 2,
      title: "JavaScript Variables",
      icon: "📦",
      content: "2.1 How Variables Work\nA variable allows a program to \"remember\" information so it can be used or changed later. In JavaScript, this process looks like this:\n**Example:**```javascript\nlet userName = \"Gemini\"; // Declaring a variable and assigning a string\nconst pi = 3.14;        // Declaring a constant value\n```\n**Declaration:** Telling the computer to reserve a spot in memory (e.g., let).\n**Assignment:** Using the = operator to store a value in that spot.\n**Initialization:** The very first time you put a value into a variable.\n2.2 Declaration Keywords: var, let, and const\nHistorically, JavaScript only had var. Modern JavaScript (ES6+) introduced let and const to fix common bugs.\n**var (Legacy):** Function-scoped. It can be re-declared and updated. It is generally avoided in modern professional code.\n**let (Modern):** Block-scoped. It can be updated but not re-declared within the same scope. Use this when the value will change.\n**const (Modern):** Block-scoped. It cannot be updated or re-declared. Professionals use this by default for almost everything.\n2.3 Scope: Where do your variables live?\nScope determines the visibility or accessibility of variables from different parts of your code.\n**Global Scope:** A variable declared outside any function or block. It is accessible from anywhere.\n**Function Scope:** Variables declared inside a function are only available within that function.\n**Block Scope:** Variables declared with let or const inside { } cannot be accessed from outside those brackets.\n2.4 Hoisting: The \"Lifting\" Mechanism\nHoisting is a behavior where declarations are moved to the top of their scope during compilation.\n**var Hoisting:** If you try to use a var before it is declared, it returns undefined.\n**let & const Hoisting:** They enter a Temporal Dead Zone (TDZ). Accessing them before definition results in a ReferenceError.\n2.5 Variable Declaration Keywords\n|||\nKeyword | Scope | Re-assignable? | Redeclarable? | Professional Use Case\n`const` | `Block {}` | **No** | No | **The Standard.** Use for values that shouldn't change (API keys, fixed settings).\n`let` | `Block {}` | **Yes** | No | Use for values that **will** change (counters, loop variables, toggles).\n`var` | Function | **Yes** | Yes | **Legacy.** Avoid using this in modern projects as it causes scope-related bugs.\n|||"
    },
    {
      id: 3,
      title: "JavaScript Data Types",
      icon: "🔢",
      // eslint-disable-next-line no-template-curly-in-string
      content: "3.1 Primitives (Simple & Immutable)\nPrimitive values are the basic building blocks. They hold a single, simple value and are immutable.\n**String:** Used for text.\n**Pro-Tip:** Modern JS uses Template Literals (using backticks `) which allow you to inject variables directly: `Hello, ${name}`.\n**Number:** JS uses one type for all numbers—whether they are integers (5) or decimals (5.5).\n**Boolean:** Logic gates. It can only be true or false. Essential for \"If/Else\" statements.\n**Null & Undefined (The \"Empty\" Types):**\n**undefined:** Means a variable has been declared but has not yet been given a value.\n**null:** An intentional assignment that represents \"nothing.\"\n3.2 Complex Types (Objects & Arrays)\nThese types are \"reference types\" because they can store collections of data.\n**Objects:** Collections of key-value pairs. They represent real-world entities.\n**Example:**```javascript\nconst car = { brand: \"Tesla\", model: \"Model 3\" };\n```\n**Arrays:** Ordered lists of data. You access items by their position (index), starting at 0.\n**Example:**```javascript\nconst fruits = [\"Apple\", \"Banana\", \"Cherry\"];\n```\n3.3 Type Coercion: The \"Secret\" Conversion\nJavaScript is a \"weakly typed\" language, meaning it tries to be helpful by converting types automatically.\n**Implicit Coercion:** If you try 5 + \"5\", JavaScript converts the number to a string and gives you \"55\". This often causes bugs.\n**The Equality Solution:**\n**(Loose Equality):** Checks only the value. (5 == \"5\" is true).\n**=== (Strict Equality):** Checks both the value and the type. (5 === \"5\" is false).\n**Professional Rule:** Always use === to avoid unpredictably errors caused by coercion.\n3.4 Summary Table: Data Types at a Glance\n|||\nType | Example | Use Case\nString | \"Hello\" | Storing names, messages, or IDs.\nNumber | 42 | Math, prices, and counting.\nBoolean | true | Checkboxes, login status.\nObject | { id: 1 } | Grouping related data.\nArray | [1, 2, 3] | Storing a list of items.\nNull | null | Intentionally clearing a value.\n|||"
    },
    {
      id: 4,
      title: "JavaScript Functions",
      icon: "🧩",
      content: "4.1What is a Function?\nA Function is a reusable block of code designed to perform a particular task.It is executed when \"something\" invokes it(calls it).Think of it as a Sub-Program inside your main application.4.2Types of Functions**1.Function Declaration**This is the traditional way to define a function.It is hoisted,meaning you can call it before it's defined in your code.\n**Example:**```javascript\nfunction calculateTotal(price,tax){return price+tax;}\n```**2.Function Expression**Here,a function is stored inside a variable.It is not hoisted,making your code's execution flow more predictable.\n**Example:**```javascript\nconst getGreeting=function(name){return \"Hello \"+name;};\n```**3.Arrow Functions(ES6)**This is the most common type used in React Components.It has a shorter syntax and does not have its own this keyword.\n**Example:**```javascript\nconst welcome=(user)=>`Welcome back, ${user}!`;\n```**4.Anonymous Functions**These are functions without a name.They are usually used as Callbacks—passed into other functions to be executed later.\n**Example:**```javascript\n<button onClick={()=>console.log(\"Clicked!\")}>Click Me</button>\n```"
    },
    { id: 5, title: "JavaScript Events", icon: "🖱️", content: "5.1 What is a JavaScript Event?\nAn Event is a \"signal\" sent by the browser to notify your code that something has happened. This could be triggered by the user (a click) or the system (a page finishing its load).\nThe Event Listener: To respond to an event, you attach a \"listener\" to an HTML element. When the event occurs, the listener executes a specific function (often called an Event Handler).\n5.2 Common Types of Events\nAs a developer, you will spend most of your time working with these four categories:\nMouse Events:\n- click: User clicks an element.\n- dblclick: User double-clicks.\n- mouseover: User moves the mouse over an element (hover).\nKeyboard Events:\n- keydown: User presses a key.\n- keyup: User releases a key.\nForm Events:\n- submit: User submits a form (e.g., a login or search).\n- change: An input value changes (e.g., a dropdown selection).\nWindow/Document Events:\n- DOMContentLoaded: The HTML is fully loaded and parsed.\n- scroll: User scrolls up or down the page.\n2. Event Syntax: The Professional Way\nThere are three ways to handle events, but only one is recommended for modern projects.\nA. Inline Event Handlers (Legacy)\nWritten directly in the HTML. Avoid this in professional projects because it mixes logic with structure.\nHTML\n<button onclick=\"alert('Clicked!')\">Click Me</button>\nB. Event Listener (Modern Standard)\nThe addEventListener() method is the best practice. It keeps your JavaScript separate from your HTML and allows you to add multiple listeners to the same element.\nJavaScript\nconst btn = document.querySelector(\".run-btn\");\nbtn.addEventListener(\"click\", (event) => {\n  console.log(\"Code is running...\");\n});\n3. The \"Event Object\" (e)\nWhen an event occurs, JavaScript automatically passes an Event Object to your handler function. This object contains vital information:\n- event.target: The exact element that was clicked.\n- event.type: The name of the event (e.g., \"click\").\n- event.key: Which specific key was pressed (for keyboard events).\n4. Event Bubbling vs. Capturing\nWhen you click a button inside a \u003cdiv\u003e, you are technically clicking both.\n- Bubbling: The event starts at the target (the button) and \"bubbles up\" to the parents.\n- Capturing: The event travels from the top (the document) down to the target.\nStop Propagation: If you want an event to stop at the button and not trigger the parent's click event, you use event.stopPropagation().\n5. Prevent Default\nSome elements have natural behaviors. For example, a link (\u003ca\u003e) automatically goes to a new URL. In a React app, you often want to stop this behavior to handle the logic yourself using event.preventDefault().\nJavaScript\nform.addEventListener(\"submit\", (e) => {\n  e.preventDefault(); // Stops the page from refreshing\n  console.log(\"Form data processed!\");\n});\n(these keep in the java script 5th lesson)" }
  ]
};
